"""Opt-in DouZero V3 Hybrid contracts and H1 public card-play model."""

from .adaptive_dmc import (
    ADMC_DISABLED,
    ADMC_PAPER_RATIO,
    ADMC_SAFE_HYBRID,
    AdaptiveDMCConfig,
    AdaptiveDMCResult,
    adaptive_dmc_loss,
    transform_dmc_target,
)

from .checkpoint import (
    V3_HYBRID_H1_CHECKPOINT_FORMAT,
    h1_compatibility_identity,
    load_v3_hybrid_public_checkpoint,
    save_v3_hybrid_public_checkpoint,
)
from .belief_checkpoint import (
    V3_H4_PUBLIC_CHECKPOINT_FORMAT,
    load_v3_h4_public_checkpoint,
    save_v3_h4_public_checkpoint,
)
from .belief_policy import V3BeliefPolicy
from .config import (
    BELIEF_FEEDBACK_ALL,
    BELIEF_FEEDBACK_FARMERS,
    BELIEF_FEEDBACK_NONE,
    CHANNEL_GATE_NONE,
    CHANNEL_GATE_SE,
    DMC_TARGET_RAW,
    DMC_TARGET_SIGNED_LOG,
    HISTORY_ENCODER_LSTM,
    HISTORY_ENCODER_TRANSFORMER,
    V3HybridModelConfig,
)

from .contract import (
    V3_HYBRID_CHECKPOINT_KIND,
    V3_HYBRID_CONTRACT_VERSION,
    V3_HYBRID_FEATURE_VERSION,
    V3_HYBRID_LOSS_TERMS,
    V3_HYBRID_MODEL_VERSION,
    V3_HYBRID_OBSERVATION_SCHEMA_HASH,
    V3_HYBRID_OBSERVATION_SCHEMA_VERSION,
    V3_HYBRID_PHASES,
    V3HybridCompatibilityIdentity,
    assert_v3_hybrid_compatible,
    v3_hybrid_semantic_contract,
)
from .export import ExportableV3HybridModel, export_v3_hybrid_padded
from .model import V3_HYBRID_ROLES, V3HybridModel
from .output import BatchedV3HybridModelOutput, V3HybridModelOutput
from .h2_learner import (
    V3_H2_TRAINER_CHECKPOINT_FORMAT,
    V3_H2_TRAINING_CONTRACT,
    AdaptiveDMCCumulativeStats,
    V3H2Learner,
    V3H2LearnerConfig,
    V3H2StepMetrics,
    h2_training_identity,
)
from .replay import (
    V3_H2_REPLAY_SCHEMA_VERSION,
    V3_H2_REPLAY_SEMANTICS,
    AdaptiveSnapshotProvenance,
    PendingV3Transition,
    V3ReplayBuffer,
    V3ReplayTransition,
    capture_adaptive_transition,
    capture_plain_transition,
)

__all__ = [
    "V3_HYBRID_CHECKPOINT_KIND",
    "V3_HYBRID_CONTRACT_VERSION",
    "V3_HYBRID_FEATURE_VERSION",
    "V3_HYBRID_LOSS_TERMS",
    "V3_HYBRID_MODEL_VERSION",
    "V3_HYBRID_OBSERVATION_SCHEMA_HASH",
    "V3_HYBRID_OBSERVATION_SCHEMA_VERSION",
    "V3_HYBRID_PHASES",
    "V3HybridCompatibilityIdentity",
    "assert_v3_hybrid_compatible",
    "v3_hybrid_semantic_contract",
    "CHANNEL_GATE_NONE",
    "CHANNEL_GATE_SE",
    "DMC_TARGET_RAW",
    "DMC_TARGET_SIGNED_LOG",
    "HISTORY_ENCODER_LSTM",
    "HISTORY_ENCODER_TRANSFORMER",
    "V3HybridModelConfig",
    "BELIEF_FEEDBACK_NONE",
    "BELIEF_FEEDBACK_FARMERS",
    "BELIEF_FEEDBACK_ALL",
    "V3_HYBRID_ROLES",
    "V3HybridModel",
    "V3HybridModelOutput",
    "BatchedV3HybridModelOutput",
    "V3_HYBRID_H1_CHECKPOINT_FORMAT",
    "h1_compatibility_identity",
    "save_v3_hybrid_public_checkpoint",
    "load_v3_hybrid_public_checkpoint",
    "V3_H4_PUBLIC_CHECKPOINT_FORMAT",
    "V3BeliefPolicy",
    "save_v3_h4_public_checkpoint",
    "load_v3_h4_public_checkpoint",
    "ExportableV3HybridModel",
    "export_v3_hybrid_padded",
    "ADMC_DISABLED",
    "ADMC_PAPER_RATIO",
    "ADMC_SAFE_HYBRID",
    "AdaptiveDMCConfig",
    "AdaptiveDMCResult",
    "adaptive_dmc_loss",
    "transform_dmc_target",
    "V3_H2_REPLAY_SCHEMA_VERSION",
    "V3_H2_REPLAY_SEMANTICS",
    "AdaptiveSnapshotProvenance",
    "PendingV3Transition",
    "V3ReplayTransition",
    "V3ReplayBuffer",
    "capture_plain_transition",
    "capture_adaptive_transition",
    "V3_H2_TRAINER_CHECKPOINT_FORMAT",
    "V3_H2_TRAINING_CONTRACT",
    "AdaptiveDMCCumulativeStats",
    "V3H2LearnerConfig",
    "V3H2StepMetrics",
    "V3H2Learner",
    "h2_training_identity",
]
